const TREE_DATA = [
  {
    "id": 1,
    "binomial": "Cycas circinalis L.",
    "family": "Cycadaceae",
    "common": "sago palm",
    "tamil": "பனைப் பெரணி",
    "flowering": "December to February or May to November",
    "fruiting": "February-August",
    "medicinal": "Whole Plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 2,
    "binomial": "Calophyllum L",
    "family": "Calophyllaceae",
    "common": "Alexandrian laurel",
    "tamil": "புன்னை மரம்",
    "flowering": "April-June or October-December",
    "fruiting": "July to September",
    "medicinal": "Seed ,Leaf, Bark.",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 3,
    "binomial": "Terminalia elliptica Willd.",
    "family": "Combretaceae",
    "common": "Crocodile Bark Tree",
    "tamil": "கருமருது",
    "flowering": "April to August",
    "fruiting": "April to May",
    "medicinal": "Bark, leaf",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 4,
    "binomial": "Diospyros ebenum J.Koenig",
    "family": "Ebenaceae",
    "common": "Indian Ebony",
    "tamil": "கருங்காலி",
    "flowering": "April and May",
    "fruiting": "September to November",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 5,
    "binomial": "Filicium decipiens (Wight & Arn.) Thwaites",
    "family": "Sapindaceae",
    "common": "Fern Tree",
    "tamil": "ஆதடலி மரம்",
    "flowering": "October–December, March–May",
    "fruiting": "October to December",
    "medicinal": "Bark",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 6,
    "binomial": "Millingtonia hortensis L.f.",
    "family": "Bignoniaceae",
    "common": "Tree Jasmine",
    "tamil": "மரமல்லி",
    "flowering": "October–December, June to January",
    "fruiting": "October to December",
    "medicinal": "flower",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 7,
    "binomial": "Mallotus philippensis (Lam.) Müll.Arg.",
    "family": "Euphorbiaceae",
    "common": "Kamala Tree",
    "tamil": "செந்தூரம்",
    "flowering": "January to March and June to September.",
    "fruiting": "January to April or July to August",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 8,
    "binomial": "Elaeagnus conferta Roxb.",
    "family": "Elaeagnaceae",
    "common": "Eastern Silverberry",
    "tamil": "குரங்குப் பழம்",
    "flowering": "November to December.",
    "fruiting": "March to April.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 9,
    "binomial": "Hydnocarpus pentandrus (Buch.-Ham.) Oken",
    "family": "Achariaceae",
    "common": "Jangli Almond",
    "tamil": "மரவெட்டி",
    "flowering": "January to May",
    "fruiting": "September to December.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 10,
    "binomial": "Manilkara kauki (L.) Dubard",
    "family": "Sapotaceae",
    "common": "Bullet wood",
    "tamil": "மகிழமரம்",
    "flowering": "May-June",
    "fruiting": "June and October",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 11,
    "binomial": "Diospyros samoensis A.Gray",
    "family": "Ebenaceae",
    "common": "Indian Ebony",
    "tamil": "வக்கனை",
    "flowering": "March to July",
    "fruiting": "May to November",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 12,
    "binomial": "Dichrostachys (A.DC.) Wight & Arn.",
    "family": "Fabaceae",
    "common": "Bell mimosa",
    "tamil": "விடத்தலை மரம்",
    "flowering": "July and August.",
    "fruiting": "May to September",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 13,
    "binomial": "Acrocarpus fraxinifolius Wight & Arn.",
    "family": "Fabaceae",
    "common": "Pink cedar",
    "tamil": "நெல்றை",
    "flowering": "February to May",
    "fruiting": "July to September",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 14,
    "binomial": "Bambusa bambos (L.) Voss",
    "family": "Poaceae",
    "common": "thorny bamboo",
    "tamil": "மூங்கில்",
    "flowering": "The cycle for Bambusa bambos is approximately 43–49 years",
    "fruiting": "",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 15,
    "binomial": "Dysoxylum gotadhora (Buch.-Ham.) Mabb.",
    "family": "Meliaceae",
    "common": "Akil",
    "tamil": "அகில்",
    "flowering": "March to July",
    "fruiting": "March to January",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 16,
    "binomial": "Samanea saman (Jacq.) Merr.",
    "family": "Fabaceae",
    "common": "Rain tree",
    "tamil": "தூங்குமூஞ்சி மரம்",
    "flowering": "March to May",
    "fruiting": "May to June.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 17,
    "binomial": "Neolamarckia cadamba (Roxb.) Bosser",
    "family": "Rubiaceae",
    "common": "kadamba",
    "tamil": "கடம்பு மரம்",
    "flowering": "June to August",
    "fruiting": "September to December",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 18,
    "binomial": "Pongamia pinnata (L.) Pierre",
    "family": "Fabaceae",
    "common": "Pongam Tree",
    "tamil": "புங்க மரம்",
    "flowering": "April to July",
    "fruiting": "January to March",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 19,
    "binomial": "Lagerstroemia microcarpa Hance",
    "family": "Lythraceae",
    "common": "Venthekku",
    "tamil": "வெண்தேக்கு",
    "flowering": "June to February",
    "fruiting": "June to February.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 20,
    "binomial": "Sterculia foetida L.",
    "family": "Malvaceae",
    "common": "Wild Almond Tree",
    "tamil": "பீநாறி",
    "flowering": "February to May",
    "fruiting": "March to May",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 21,
    "binomial": "Sapindus saponaria subsp. Saponaria",
    "family": "Sapindaceae",
    "common": "Soapnut Tree",
    "tamil": "பூந்தி",
    "flowering": "November and January",
    "fruiting": "October to December",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 22,
    "binomial": "Acacia leucophloea (Roxb.) Willd.",
    "family": "Fabaceae",
    "common": "White-Barked Acacia",
    "tamil": "வெள்வேல்",
    "flowering": "August to October",
    "fruiting": "April to June",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 23,
    "binomial": "Tectona L.f.",
    "family": "Lamiaceae",
    "common": "Teak",
    "tamil": "தேக்கு",
    "flowering": "June to August or September",
    "fruiting": "September to December.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 24,
    "binomial": "Pterocarpus marsupium Roxb.",
    "family": "Fabaceae",
    "common": "Indian Kino Tree",
    "tamil": "வேங்கை மரம்",
    "flowering": "November to March",
    "fruiting": "June to December",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 25,
    "binomial": "Dalbergia andapensis Bosser & R.Rabev",
    "family": "Fabaceae",
    "common": "Indian Rosewood",
    "tamil": "ஈட்டி மரம்",
    "flowering": "January to March",
    "fruiting": "November to February",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 26,
    "binomial": "Schleichera oleosa (Lour.) Oken",
    "family": "Sapindoideae",
    "common": "Ceylon oak",
    "tamil": "பூவம்",
    "flowering": "January to April",
    "fruiting": "February to August",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 27,
    "binomial": "Albizia amara (Roxb.) Boivin",
    "family": "Fabaceae",
    "common": "Arappu",
    "tamil": "அரப்பு",
    "flowering": "February to May",
    "fruiting": "May to July",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 28,
    "binomial": "Syzygium cumini (L.) Skeels",
    "family": "Myrtaceae",
    "common": "Jamun",
    "tamil": "நாவல்",
    "flowering": "March to April",
    "fruiting": "June to July",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 29,
    "binomial": "Gliricidia sepium (Jacq.) Kunth",
    "family": "Fabaceae",
    "common": "Mexican lilac",
    "tamil": "சீமைக் கிளுவை",
    "flowering": "February to April",
    "fruiting": "November to March",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 30,
    "binomial": "Pterospermum reticulatum Wight & Arn.",
    "family": "Malvaceae",
    "common": "Mulipolavu",
    "tamil": "வெண்ணாந்தை,முலிபொலவு",
    "flowering": "February to April",
    "fruiting": "March to November",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 31,
    "binomial": "Alstonia scholaris (L.) R.Br.",
    "family": "Apocynaceae",
    "common": "devil tree",
    "tamil": "ஏழிலைப்பாலை",
    "flowering": "November to December",
    "fruiting": "May to July.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 32,
    "binomial": "Strychnos nux-vomica L.",
    "family": "Loganiaceae",
    "common": "snakewood tree",
    "tamil": "எட்டி மரம்",
    "flowering": "March to May.",
    "fruiting": "November to February",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 33,
    "binomial": "Vitex parviflora A.Juss.",
    "family": "Lamiaceae",
    "common": "Peacock's foot tree",
    "tamil": "மயிலாடி",
    "flowering": "April to May",
    "fruiting": "July to August or September to January",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 34,
    "binomial": "Bombax L.",
    "family": "Bombacaceae",
    "common": "Red silk cotton",
    "tamil": "முள் இலவம்",
    "flowering": "January to March/April",
    "fruiting": "April to June",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 35,
    "binomial": "Ailanthus triphysa (Dennst.) Alston",
    "family": "Simaroubaceae",
    "common": "Malabar Tree of Heaven",
    "tamil": "மட்டிப்பால்",
    "flowering": "December to May",
    "fruiting": "March to April",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 36,
    "binomial": "Swietenia mahagoni (L.) Jacq.",
    "family": "Meliaceae",
    "common": "mahogany",
    "tamil": "மஹோகனி",
    "flowering": "April – June",
    "fruiting": "October - January",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 37,
    "binomial": "Albizia lebbeck (L.) Benth.",
    "family": "Mimosaceae",
    "common": "Lebbek tree",
    "tamil": "வாகை மரம்",
    "flowering": "April to June or September.",
    "fruiting": "September–October",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 38,
    "binomial": "Santalum album L.",
    "family": "Santalaceae",
    "common": "sandalwood",
    "tamil": "சந்தனம்",
    "flowering": "March to April and again from September to October",
    "fruiting": "September–October and March–April",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 39,
    "binomial": "Garcinia indica (Thouars) Choisy",
    "family": "Clusiaceae.",
    "common": "Wild Mangosteen",
    "tamil": "முருகல்",
    "flowering": "November to February",
    "fruiting": "April to June",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 40,
    "binomial": "Dalbergia lanceolaria subsp. paniculata (Roxb.) Thoth.",
    "family": "Fabaceae",
    "common": "Patri",
    "tamil": "பனிவாகை",
    "flowering": "March",
    "fruiting": "February to October",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 41,
    "binomial": "Butea monosperma (Lam.) Kuntze",
    "family": "Fabaceae",
    "common": "Flame of the Forest",
    "tamil": "பொரசு",
    "flowering": "January to March",
    "fruiting": "May to June",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 42,
    "binomial": "Harpullia arborea (Blanco) Radlk.",
    "family": "sapindaceae",
    "common": "Tulip-Wood Tree",
    "tamil": "நெய்க்கொட்டை",
    "flowering": "October to December",
    "fruiting": "June to July.",
    "medicinal": "Whole parts",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 43,
    "binomial": "Hopea parviflora Bedd.",
    "family": "Dipterocarpaceae",
    "common": "Malabar Ironwood",
    "tamil": "இருபகம்",
    "flowering": "January to March",
    "fruiting": "January and June",
    "medicinal": "Whole parts",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 44,
    "binomial": "Madhuca longifolia (L.) J.F.Macbr.",
    "family": "Sapotaceae",
    "common": "Indian Butter Tree",
    "tamil": "இலுப்பை",
    "flowering": "February to April",
    "fruiting": "August to September",
    "medicinal": "Whole parts",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 45,
    "binomial": "Terminalia arjuna (Roxb. ex DC.) Wight & Arn.",
    "family": "Combretaceae",
    "common": "Arjuna tree",
    "tamil": "நீர்மருது",
    "flowering": "April to July",
    "fruiting": "November to March",
    "medicinal": "Whole parts",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 46,
    "binomial": "Caryota urens L.",
    "family": "Arecaceae.",
    "common": "fishtail palm",
    "tamil": "கூந்தற்பனை",
    "flowering": "January to April",
    "fruiting": "December and August",
    "medicinal": "Whole parts",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 47,
    "binomial": "Terminalia bellirica (Gaertn.) Roxb.",
    "family": "Combretaceae",
    "common": "Bedda nut tree",
    "tamil": "தான்றிக்காய்",
    "flowering": "February to April.",
    "fruiting": "November to February or December to March",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 48,
    "binomial": "Dimocarpus longan Lour.",
    "family": "Sapindaceae",
    "common": "Dragon Eye",
    "tamil": "செம்பூவம்",
    "flowering": "April-May",
    "fruiting": "July-September",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 49,
    "binomial": "Canarium strictum Roxb.",
    "family": "Burseraceae",
    "common": "Black Dammar",
    "tamil": "கருங்குங்கிலியம்",
    "flowering": "November and January",
    "fruiting": "February to April",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 50,
    "binomial": "Bridelia retusa (L.) A.Juss.",
    "family": "Phyllanthaceae",
    "common": "Spinous Kino",
    "tamil": "முள்வேங்கை",
    "flowering": "May to August",
    "fruiting": "January to February",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 51,
    "binomial": "Streblus asper Lour.",
    "family": "Moraceae",
    "common": "Sandpaper Tree",
    "tamil": "பராய்",
    "flowering": "January to March and again from July to September",
    "fruiting": "April to June.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 52,
    "binomial": "Bauhinia racemosa Lam.",
    "family": "Fabaceae",
    "common": "Bidi Leaf Tree",
    "tamil": "ஆத்தி",
    "flowering": "February to May/June",
    "fruiting": "November and December.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 53,
    "binomial": "Artabotrys hexapetalus (L.f.) Bhandari",
    "family": "Annonaceae",
    "common": "Manoranjini",
    "tamil": "மனோரஞ்சிதம்",
    "flowering": "April to August/September",
    "fruiting": "September to February",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 54,
    "binomial": "Cassia fistula L.",
    "family": "Fabaceae",
    "common": "Golden Shower Tree",
    "tamil": "சரக்கொன்றை",
    "flowering": "April to June.",
    "fruiting": "December to April",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 55,
    "binomial": "Grewia tiliifolia A.Rich.",
    "family": "Malvaceae",
    "common": "Common Indian Linden",
    "tamil": "தடசு",
    "flowering": "February to June",
    "fruiting": "July-September",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 56,
    "binomial": "Asparagus racemosus Willd. (Xylia xylocarpa.)",
    "family": "Fabaceae",
    "common": "Burma Ironwood",
    "tamil": "இருள் மரம்",
    "flowering": "March to May",
    "fruiting": "December to July",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 57,
    "binomial": "Annona Muricata L.",
    "family": "Annonaceae",
    "common": "Soursop",
    "tamil": "முள் சீதா",
    "flowering": "almost year-round",
    "fruiting": "late summer (July-September),winter (December-February)",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 58,
    "binomial": "Ziziphus mauritiana Lam.",
    "family": "Rhamnaceae",
    "common": "Indian Plum",
    "tamil": "இலந்தை",
    "flowering": "September to November",
    "fruiting": "October/November,March/April",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 59,
    "binomial": "Artocarpus gomezianus Wall. ex Trécul.",
    "family": "Moraceae",
    "common": "Mon-jack",
    "tamil": "இராப்பலா",
    "flowering": "March to June.",
    "fruiting": "June to August",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 60,
    "binomial": "Toona M.Roem. (Toona ciliata )",
    "family": "Meliaceae",
    "common": "Indian mahogany, Red cedar",
    "tamil": "சந்தன வேம்பு",
    "flowering": "February to May",
    "fruiting": "February and May",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 61,
    "binomial": "Artocarpus hirsutus Lam.",
    "family": "Moraceae",
    "common": "Wild Jackfruit",
    "tamil": "அயனிப்பலா",
    "flowering": "December to March.",
    "fruiting": "May and June",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 62,
    "binomial": "Ficus virens Aiton.",
    "family": "Moraceae",
    "common": "White Fig",
    "tamil": "மலை-இச்சி",
    "flowering": "February to May",
    "fruiting": "December and March",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 63,
    "binomial": "Majidea zanguebarica Kirk ex Oliv.",
    "family": "Sapindaceae",
    "common": "Velvet Seed Tree",
    "tamil": "கருமுத்து மரம்",
    "flowering": "January to June",
    "fruiting": "January to June",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 64,
    "binomial": "Chrysophyllum cainito L.",
    "family": "Sapotaceae",
    "common": "Star apple",
    "tamil": "நுங்கு ஆப்பிள்",
    "flowering": "July to September/October",
    "fruiting": "December and March or April.",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 65,
    "binomial": "Ficus benghalensis L.",
    "family": "Moraceae",
    "common": "Banyan Tree",
    "tamil": "ஆலமரம்",
    "flowering": "March to April.",
    "fruiting": "March to May",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  },
  {
    "id": 66,
    "binomial": "Ficus religiosa Forssk.",
    "family": "Moraceae",
    "common": "Peepal tree",
    "tamil": "அரசமரம்",
    "flowering": "November and February",
    "fruiting": "March to May",
    "medicinal": "Whole plant",
    "english": "Tamil",
    "tamilInfo": ""
  }
];
